routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return get('','');
// });

//****************** CMS-ADMIN *******************//

    Route::get('','DasbordController@admin')->name('cms.dashboard')->middleware('auth:author,super,admin');


Route::prefix('cms/')->group(function () {


    Route::resource('author', 'AuthorController')->middleware('auth:super,admin');

    Route::resource('category', 'CategoryController')->middleware('auth:admin,super');
    Route::resource('super', 'SuperAdminController')->middleware('auth:super');
    Route::resource('admin', 'AdminController')->middleware('auth:super');
    Route::put('admin/Password/{token}', 'AdminController@AdminPassword')->name('admin.password')->middleware('auth:admin,super');
    Route::put('author/Password/{token}', 'AuthorController@AuthorPassword')->name('author.password')->middleware('auth:admin,super');
    Route::get('/admin/CategoryAdmins/{token}','AdminController@AdminCategory')->name('admin.category')->middleware('auth:super');
    Route::get('/admin/AuthorAdmins/{token}','AdminController@AdminAuthor')->name('admin.author')->middleware('auth:super');
    Route::get('logouts', 'Auth\SuperAdminController@logout')->name('super.logout')->middleware('auth:super');
    Route::get('logouta', 'Auth\AdminAuthController@logout')->name('admin.logout')->middleware('auth:admin');
    Route::get('logoutA', 'Auth\AuthorAuthController@logout')->name('author.logout')->middleware('auth:author');



});


Route::prefix('super/')->namespace('Auth')->group(function () {
Route::get('login', 'SuperAdminController@showLoginView')->name('super.login_view');
Route::post('login', 'SuperAdminController@login')->name('super.post');


});

Route::prefix('admin/')->namespace('Auth')->group(function () {
Route::get('login', 'AdminAuthController@showLoginView')->name('admin.login_view');
Route::post('login', 'AdminAuthController@login')->name('admin.post');

});
// Route::get('login', 'AuthorAuthController@showLoginView')->name('author.login_view');

Route::prefix('author')->namespace('Auth')->group(function () {
Route::get('login', 'AuthorAuthController@showLoginView')->name('author.login_view');
Route::post('login', 'AuthorAuthController@login')->name('author.post');

});



Route::get('/h', function () {
    return view('cms.auth.super.login');
});



// Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/AdminController.php
<?php

namespace App\Http\Controllers;

use App\Admin;
use App\Category;
use App\Http\Requests\AdminEditRequest;
use App\Http\Requests\AdminRequest;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

class AdminController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $admins=Admin::withCount(['category','author'])->get();
        return view('cms.admins.index',['admins'=>$admins]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('cms.admins.create',['categorys'=>Category::all()]);
    }

    public function AdminCategory($token){

  $categories=Admin::where('token',$token)->first()->category()->get();

                return view('cms.categories.index',['categories'=>$categories]);

}
  public function AdminAuthor($token){

  $categories=Admin::where('token',$token)->first()->author()->get();

                return view('cms.authors.index',['authors'=>$categories]);

}


    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(AdminRequest $request)
    {
       $admin= new Admin();
        $admin->name=$request->get('name');
        $admin->email=$request->get('email');
        $admin->mobile=$request->get('mobile');
        $admin->address=$request->get('address');
        $admin->status=$request->get('status')=='on'?'Active':'Blocked';
        $admin->password=Hash::make($request->get('password'));
        $token=Str::uuid();
        $admin->token=$token;
         if($request->hasFile('image')){
         $imagefile=$request->file('image');
         $imagename=time().' '.$token.' '.' '.$imagefile->getClientOriginalName();

         $imagefile->move('images/admins',$imagename);
         $admin->image=$imagename ;
         }
         $save=$admin->save();
         if($save){
        $admin->category()->sync($request->get('category_id'));

            SuccessError::Success('تم الإنشاء بنجاح');
            return redirect()->back();
      }
      else{
          SuccessError::Error('فشل الإنشاء');
          return redirect()->back();

      }


    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Admin  $admin
     * @return \Illuminate\Http\Response
     */
    public function show(Admin $admin)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Admin  $admin
     * @return \Illuminate\Http\Response
     */
    public function edit($token)
    {
        $admin=Admin::where('token',$token)->with('category')->first();
        return view('cms.admins.edit',['admin'=>$admin,'categorys'=>Category::all()]);
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Admin  $admin
     * @return \Illuminate\Http\Response
     */
    public function update(AdminEditRequest $request, $token)
    {
        //
        // dd(444);

        $admin=Admin::where('token',$token)->first();
        $id=$admin->id;

        $request->validate([
            'email' => 'required:string|email|unique:authors,email|unique:admins,email,' . $id,
            'mobile' => 'required|numeric|unique:authors,mobile|unique:admins,mobile,'.$id,

        ],[
            'mobile.required' => 'الهاتف مطلوب',
            'mobile.numeric' => ' يجب أن يكون أرقام',
            'mobile.unique' => 'تم استخدام هذا الرقم من قبل',
             'email.required' => 'الإيميل مطلوب',
            'email.email' => 'الإيميل خاطئ',
            'email.unique' => 'هذا الحساب مسجل من قبل ',
        ]);

        $admin->name=$request->get('name');
        $admin->email=$request->get('email');
        $admin->mobile=$request->get('mobile');
        $admin->address=$request->get('address');
        $admin->status=$request->get('status')=='on'?'Active':'Blocked';
         if($request->hasFile('image')){
         $imagefile=$request->file('image');
         $imagename=time().' '.'admins_image'.$admin->token.' '.$imagefile->getClientOriginalName();

         $imagefile->move('images/admins',$imagename);
         $admin->image=$imagename ;
         }
         $save=$admin->save();
         if($save){
            $admin->category()->sync($request->get('category_id'));
            SuccessError::Success('تم التعديل بنجاح');
            return redirect()->back();
      }
      else{
          SuccessError::Error('فشل التعديل');
          return redirect()->back();

      }







    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Admin  $admin
     * @return \Illuminate\Http\Response
     */
    public function destroy($token)
    {
//  $admin=Admin::where('token',$token)->first();


       $admin=Admin::where('token',$token)->delete();
        //  $del=   $admin->delete();
   if ($admin){
              return response()->json(['icon'=>'success','title'=>'تم الحذف بنجاح  '],200);
              }else{
              return response()->json(['icon'=>'error','title'=>'فشل الحذف'],400);
              }

    }

    public function AdminPassword(Request $request,$token){

        $request->validate([
             'password' => 'min:8',
            'confirm'=>'same:password',

        ],[
            'password.min' => 'كلمة السر يجب أن تتجاوز 8 حروف',
            'confirm.same'=>'يجب أن تكون الكلمتان متطابقتان'
        ]);

            // dd($request->token);
        $user = Admin::where('token',$token)->first();
        if($user){

             $user->password = Hash::make($request->get('password'));
        $isSaved = $user->save();
        if ($isSaved) {
            return response()->json(['icon' => 'success', 'title' => 'تم تغيير كلمة السر بنجاح'], 200);
        } else {
            return response()->json(['icon' => 'success', 'title' => 'فشل تغيير كلمة السر'], 400);
        }

        }
        else{
                        return response()->json(['icon' => 'warning', 'title' => 'المستخدم غير موجود'], 400);

        }


    }
}

resources/views/cms/admins/create.blade.php
@extends('cms.parent')
@section('title', 'المسؤول')

@section('content')
    <div id="main-content">
        <div class="container-fluid">
            <div class="block-header">
                <div class="row clearfix">
                    <div class="col-md-6 col-sm-12">
                        <h1 style="font-size: 20px">آدمن جديد</h1>
                        <nav aria-label="breadcrumb">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="#" style="font-size: 20px">الرئيسية</a></li>
                                <li class="breadcrumb-item"><a href="{{ route('admin.index') }}"
                                        style="font-size: 20px">المسؤولين</a></li>
                                <li class="breadcrumb-item active" aria-current="page" style="font-size: 20px"> أدمن جديد
                                </li>
                            </ol>
                        </nav>
                    </div>
                    <div class="col-md-6 col-sm-12 text-right hidden-xs">
                        {{-- <a
                            href="https://themeforest.net/item/oculux-bootstrap-4x-admin-dashboard-clean-modern-ui-kit/23091507"
                            class="btn btn-sm btn-success" title="Themeforest"><i class="icon-basket"></i> Buy Now</a>
                        --}}
                    </div>
                </div>
            </div>

            <div class="row clearfix">
                <div class="col-sm-12">
                    <div class="card">
                        <div class="body">
                            <form method="POST" action="{{ route('admin.store') }}" enctype="multipart/form-data">



                                @if (session()->has('message'))
                                    <div class="alert {{ session()->get('status') }} alert-dismissible fade show"
                                        role="alert">
                                        <span> {{ session()->get('message') }}</span>
                                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                @endif
                                @csrf
                                <div class="form-group row">
                                    <div class="col-md-10 col-sm-10">

                                        <div class="form-group" id="dd">
                                            <label style="font-size: 20px">الإسم</label>
                                            <input type="text"
                                                class="form-control hosam {{ $errors->first('name') ? 'is-invalid' : '' }}"
                                                value="{{ old('name') }}" style="font-size: 20px" name="name"
                                                placeholder=" ادخل الإسم رباعي ">
                                            <div id="errorname" class="text-danger">{{ $errors->first('name') }}</div>
                                        </div>

                                        <div class="form-group">
                                            <label style="font-size: 20px"> الإيميل</label>
                                            <input type="email"
                                                class="form-control hosam {{ $errors->first('email') ? 'is-invalid' : '' }}"
                                                value="{{ old('email') }}" style="font-size: 20px" name="email"
                                                placeholder="الإيميل الشخصي">
                                            <div id="erroremail" class="text-danger">{{ $errors->first('email') }}</div>
                                        </div>
                                        <div class="form-group">
                                            <label style="font-size: 20px">رقم الهاتف</label>
                                            <input type="tel"
                                                class="form-control hosam {{ $errors->first('mobile') ? 'is-invalid' : '' }}"
                                                value="{{ old('mobile') }}" style="font-size: 20px" name="mobile"
                                                placeholder="أدخل رقم الهاتف">
                                            <div id="errormobile" class="text-danger">{{ $errors->first('mobile') }}</div>
                                        </div>

                                        <div class="form-group">
                                            <label style="font-size: 20px">العنوان</label>
                                            <input type="text"
                                                class="form-control hosam {{ $errors->first('address') ? 'is-invalid' : '' }}"
                                                value="{{ old('address') }}" style="font-size: 20px" name="address"
                                                placeholder="ادخل العنوان">
                                            <div id="erroraddress" class="text-danger">{{ $errors->first('address') }}</div>
                                        </div>

                                        <div class="row clearfix">
                                            <div class="col-lg-12">
                                                <input type="file" width="590px" height="390px" class="dropify"
                                                    name="image">
                                                <div id="errorimage" class="text-danger">{{ $errors->first('image') }}</div>
                                            </div>

                                        </div>
                                        <div class="form-group">
                                            <label style="font-size:  20px"> كلمة السر</label>
                                            <input type="password"
                                                class="form-control hosam {{ $errors->first('password') ? 'is-invalid' : '' }}"
                                                style="font-size: 20px" name="password">
                                            <div id="errorpassword" class="text-danger ">{{ $errors->first('password') }}</div>
                                        </div>
                                        <div class="form-group">
                                            <label style="font-size: 20px"> تأكيد كلمة السر</label>
                                             <input type="password"
                                                class="form-control hosam {{ $errors->first('password2') ? 'is-invalid' : '' }}"
                                                style="font-size: 20px" name="password2">
                                            <div id="errorpassword2" class="text-danger">{{ $errors->first('password2') }}</div>
                                        </div>
                                     <div class="form-group">
                                    <label>الفئات المتاحة</label>
                                    <div class="multiselect_div">
                                        <select id="multiselect1" name="category_id[]" class="multiselect" multiple="multiple">
                                            @foreach ($categorys as $item)

                                         <option  value="{{$item->id}}" {{(collect(old('category_id'))->contains($item->id)) ? "selected":""}}>{{$item->name}}</option>


                                            @endforeach

                                        </select>
                                    </div>
                                </div>
                                        <div class="form-group">
                                            <label style="font-size: 20px">حالة الحساب</label>
                                            <div class="custom-control custom-switch">
                                                <input type="checkbox" class="custom-control-input" name="status"
                                                    id="status" @if (old('status') == 'on')
                                                checked @endif>
                                                <label class="custom-control-label" style="font-size: 20px"
                                                    for="status">مُفعل</label>

                                            </div>
                                        </div>

                                    </div>
                                </div>
                                <div>
                                    <button style="font-size: 20px" class="btn btn-sm btn-primary" type="submit"> تسجيل
                                    </button>


                                </div>

                            </form>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
@endsection
@section('script')
    <script>
        function error() {
            document.getElementById('error').hidden = true;
        }

        $(".hosam").keyup(function() {
            document.getElementById('errorname').hidden = true;
            document.getElementById('erroremail').hidden = true;
            document.getElementById('erroraddress').hidden = true;
            document.getElementById('errormobile').hidden = true;
            document.getElementById('errorpassword').hidden = true;
            document.getElementById('errorpassword2').hidden = true;
            document.getElementById('errorimage').hidden = true;


        });
          $(".hosam").click(function() {
            document.getElementById('errorname').hidden = true;
            document.getElementById('erroremail').hidden = true;
            document.getElementById('erroraddress').hidden = true;
            document.getElementById('errormobile').hidden = true;
            document.getElementById('errorpassword').hidden = true;
            document.getElementById('errorpassword2').hidden = true;
            document.getElementById('errorimage').hidden = true;


        });

    </script>

@endsection

resources/views/cms/admins/index.blade.php
@extends('cms.parent')
@section('title','المسؤولين')
@section('style')

<link rel="stylesheet" href="{{asset('cms/assets/vendor/jquery-datatable/dataTables.bootstrap4.min.css')}}">
<link rel="stylesheet" href="{{asset('cms/assets/vendor/jquery-datatable/fixedeader/dataTables.fixedcolumns.bootstrap4.min.css')}}">
<link rel="stylesheet" href="{{asset('cms/assets/vendor/jquery-datatable/fixedeader/dataTables.fixedheader.bootstrap4.min.css')}}">
<link rel="stylesheet" href="{{asset('cms/assets/vendor/sweetalert/sweetalert.css')}}"/>

    <style>
    td.details-control {
    background: url('http://127.0.0.1:8000/cms/assets/images/details_open.png') no-repeat center center;
    cursor: pointer;
}
    tr.shown td.details-control {
        background: url('http://127.0.0.1:8000/cms/assets/images/details_close.png') no-repeat center center;
    }
</style>
@endsection
@section('content')

    <div id="main-content">
        <div class="container-fluid">
            <div class="block-header">
                <div class="row clearfix">
                    <div class="col-md-6 col-sm-12">
                        <h1>Admins</h1>
                        <nav aria-label="breadcrumb">
                            <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="{{route('author.index')}}">ِAuthors</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Admins</li>
                            </ol>
                        </nav>
                    </div>

                </div>
            </div>

            <div class="row clearfix">

                <div class="col-lg-12">
                    <div class="card">

                        <div class="body">
                            <div class="table-responsive">
                                <table class="table table-striped table-hover dataTable js-exportable">
                                    <thead>
                                        <tr>
                                            <th>#</th>
                                          <th>Name</th>
                                          <th>Image</th>
                                        <th>Authors</th>
                                        <th>Categories</th>
                                            <th>Email</th>
                                            <th>Mobile</th>
                                            <th>Status</th>
                                            <th>Address</th>
                                            <th>CreatedAt</th>
                                             <th>Settings</th>
                                        </tr>
                                    </thead>
                                    <tfoot>
                                        <tr>
                                            <th>#</th>
                                            <th>Name</th>
                                            <th>Image</th>
                                            <th>Authors</th>
                                            <th>Categories</th>
                                            <th>Email</th>
                                            <th>Mobile</th>
                                            <th>Status</th>
                                            <th>Address</th>
                                            <th>CreatedAt</th>
                                            <th>Settings</th>

                                        </tr>
                                    </tfoot>
                                    <tbody>
                                        <span hidden>{{$i=0}}</span>
                                            @foreach ($admins as $admin)
                                    <span hidden>{{$i++}}</span>

                                        <tr>
                                        <td>{{$i}}</td>
                                            <td>{{$admin->name}}</td>
                                               <td class="w60">
                                            <img src="{{url('images/admins/'.$admin->image)}}" data-toggle="tooltip" data-placement="top" title="{{$admin->name}}" alt="{{$admin->name}}" class="w35 h35 rounded">
                                        </td>
                                                 <td>
                                            <a class="btn btn-info btn-sm"

                                               href="{{route('admin.author',[$admin->token])}}">
                                                <i class="icon-map">
                                                </i>
                                                ({{$admin->author_count}}) Author/s
                                            </a>
                                            <span class="badge badge-dark"></span>
                                        </td>
                                                   <td>
                                            <a class="btn btn-success btn-sm"

                                               href="{{route('admin.category',[$admin->token])}}">
                                                <i class="icon-map">
                                                </i>
                                                ({{$admin->category_count}}) Category/s
                                            </a>
                                            <span class="badge badge-dark"></span>
                                        </td>
                                            <td>{{$admin->email}}</td>
                                            <td>{{$admin->mobile}}</td>
                                            <td>
                                                     @if($admin->status=='Active')
                                        <span style="font-size: 17px" class="badge badge-success">نشطة</span>
                                        @else
                                    <span style="font-size: 17px" class="badge badge-danger">متوقفة</span>
                                        @endif

                                            </td>
                                            <td>{{$admin->address}}</td>
                                            <td>{{$admin->created_at}}</td>
                                            <td>

                                        <a href="{{route('admin.edit',[$admin->token])}}" type="button" style="font-size: 20px" class="btn btn-sm btn-default" title="تعديل"><i class="fa fa-edit"></i> تعديل</a>
                                        <a onclick="confirmDelete(this, '{{$admin->token}}')" type="button" style="font-size: 20px" class="btn btn-sm btn-default js-sweetalert" title="حذف" data-type="confirm"><i class="fa fa-trash-o text-danger"> حذف </i></a>


                                            </td>
                                        </tr>
                                           @endforeach

                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>

@endsection
@section('script')
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>

    <script>
        function confirmDelete(app, id) {
            Swal.fire({
                title: 'هل انت متأكد من الحذف ؟',
                text: "لن تكون قادرا على استرجاعها",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'حذف',
                cancelButtonText:'تراجع'
            }).then((result) => {
                if (result.value) {
                    deletecategory(app, id)
                }
            })
        }

        function deletecategory(app, id) {
            axios.delete('/cms/admin/' + id)
                .then(function (response) {
                    // handle success (Status Code: 200)
                    console.log(response);
                    console.log(response.data);
                    showMessage(response.data);
                    app.closest('tr').remove();
                })
                .catch(function (error) {
                    // handle error (Status Code: 400)
                    console.log(error);
                    console.log(error.response.data);
                    showMessage(error.response.data);
                })
                .then(function () {
                    // always executed
                });
        }

        function showMessage(data) {
            Swal.fire({
                position: 'center',
                icon: data.icon,
                title: data.title,
                showConfirmButton: false,
                timer: 1500
            })
        }
    </script>

@endsection