routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return get('','');
// });

//****************** CMS-ADMIN *******************//

    Route::get('','DasbordController@admin')->name('cms.dashboard')->middleware('auth:author,super,admin');


Route::prefix('cms/')->group(function () {


    Route::resource('author', 'AuthorController')->middleware('auth:super,admin');

    Route::resource('category', 'CategoryController')->middleware('auth:admin,super');
    Route::resource('super', 'SuperAdminController')->middleware('auth:super');
    Route::resource('admin', 'AdminController')->middleware('auth:super');
    Route::put('admin/Password/{token}', 'AdminController@AdminPassword')->name('admin.password')->middleware('auth:admin,super');
    Route::put('author/Password/{token}', 'AuthorController@AuthorPassword')->name('author.password')->middleware('auth:admin,super');
    Route::get('/admin/CategoryAdmins/{token}','AdminController@AdminCategory')->name('admin.category')->middleware('auth:super');
    Route::get('/admin/AuthorAdmins/{token}','AdminController@AdminAuthor')->name('admin.author')->middleware('auth:super');
    Route::get('logouts', 'Auth\SuperAdminController@logout')->name('super.logout')->middleware('auth:super');
    Route::get('logouta', 'Auth\AdminAuthController@logout')->name('admin.logout')->middleware('auth:admin');
    Route::get('logoutA', 'Auth\AuthorAuthController@logout')->name('author.logout')->middleware('auth:author');



});


Route::prefix('super/')->namespace('Auth')->group(function () {
Route::get('login', 'SuperAdminController@showLoginView')->name('super.login_view');
Route::post('login', 'SuperAdminController@login')->name('super.post');


});

Route::prefix('admin/')->namespace('Auth')->group(function () {
Route::get('login', 'AdminAuthController@showLoginView')->name('admin.login_view');
Route::post('login', 'AdminAuthController@login')->name('admin.post');

});
// Route::get('login', 'AuthorAuthController@showLoginView')->name('author.login_view');

Route::prefix('author')->namespace('Auth')->group(function () {
Route::get('login', 'AuthorAuthController@showLoginView')->name('author.login_view');
Route::post('login', 'AuthorAuthController@login')->name('author.post');

});



Route::get('/h', function () {
    return view('cms.auth.super.login');
});



// Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Category extends Model
{
    //
    use SoftDeletes;
 public function admins(){
        return $this->belongsToMany(Admin::class,AdminCategory::class,'category_id','admin_id');
    }

}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Http\Requests\CategoryRequest;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;


class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $categories=[];
        if(Auth::guard('super')->check()){
             $categories=Category::all();
        }
        else{
            $categories=Auth::user()->category;
        }

        return view('cms.categories.index',['categories'=>$categories]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        // dd(88);
        //
        return view('cms.categories.create');

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CategoryRequest $request)
    {
        //


        $cate= new Category();
        $cate->name=$request->get('name');
        $cate->status=$request->get('status')=='on'?'Visible':'InVisible';
          $token=Str::uuid();
        $cate->token=$token;

         if($request->hasFile('image')){
         $imagefile=$request->file('image');
         $imagename=time().'category'.$token.' '.' '.$imagefile->getClientOriginalName();

         $imagefile->move('images/categories',$imagename);
         $cate->image=$imagename ;
         }
        $save=  $cate->save();
      if($save){
          SuccessError::Success('تم الإنشاء بنجاح');
        return redirect()->back();
      }
      else{
          SuccessError::Error('فشل الإنشاء');
          return redirect()->back();

      }




    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit($token)
    {
        //
        $category=Category::where('token',$token)->first();
        return view('cms.categories.edit',['category'=>$category]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(CategoryRequest $request, $token)
    {
        //
        $cate=Category::where('token',$token)->first();
        $cate->name=$request->get('name');
        $cate->status=$request->get('status')=='on'?'Visible':'InVisible';


         if($request->hasFile('image')){
         $imagefile=$request->file('image');
         $imagename=time().'category '.$token.' '.' '.$imagefile->getClientOriginalName();

         $imagefile->move('images/categories',$imagename);
         $cate->image=$imagename ;
         }
        $save=  $cate->save();
      if($save){
          SuccessError::Success('تم التعديل بنجاح');
        return redirect()->back();
      }
      else{
          SuccessError::Error('فشل التعديل');
          return redirect()->back();

      }


    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy($token)
    {

        $category=Category::where('token',$token)->first();

        if(!$category){
             return response()->json(['icon'=>'warning','title'=>'الفئة غير موجودة'],400);
        }
        else{
         $del=   $category->delete($category->id);
   if ($del){
              return response()->json(['icon'=>'success','title'=>'تم الحذف بنجاح  '],200);
              }else{
              return response()->json(['icon'=>'error','title'=>'فشل الحذف'],400);
              }
        }




    }
    public function gr(){
        return 5;
    }
}

resources/views/cms/categories/create.blade.php
@extends('cms.parent')
@section('title', 'الفئات')

@section('content')
    <div id="main-content">
        <div class="container-fluid">
            <div class="block-header">
                <div class="row clearfix">
                    <div class="col-md-6 col-sm-12">
                        <h1 style="font-size: 20px">فئة جديدة</h1>
                        <nav aria-label="breadcrumb">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="#" style="font-size: 20px">الرئيسية</a></li>
                                <li class="breadcrumb-item"><a href="{{ route('category.index') }}"
                                        style="font-size: 20px">الفئات</a></li>
                                <li class="breadcrumb-item active" aria-current="page" style="font-size: 20px">فئة جديدة
                                </li>
                            </ol>
                        </nav>
                    </div>
                    <div class="col-md-6 col-sm-12 text-right hidden-xs">
                        {{-- <a
                            href="https://themeforest.net/item/oculux-bootstrap-4x-admin-dashboard-clean-modern-ui-kit/23091507"
                            class="btn btn-sm btn-success" title="Themeforest"><i class="icon-basket"></i> Buy Now</a>
                        --}}
                    </div>
                </div>
            </div>

            <div class="row clearfix">
                <div class="col-sm-12">
                    <div class="card">
                        <div class="body">
                        <form method="POST" action="{{route('category.store')}}" enctype="multipart/form-data">


                                {{-- @if ($errors->any())
                                    <div class="alert alert-danger alert-dismissible fade show" role="alert">
                                        <ul>
                                            @foreach ($errors->all() as $error)
                                                <li>{{ $error }}</li>
                                            @endforeach
                                        </ul>
                                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                    </div>
                                @endif --}}
                                @if (session()->has('message'))
                                    <div class="alert {{ session()->get('status') }} alert-dismissible fade show"
                                        role="alert">
                                        <span> {{ session()->get('message') }}</span>
                                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                @endif
                                @csrf
                                <div class="form-group row">
                                    <div class="col-md-10 col-sm-10">

                                        <div class="form-group">
                                            <label style="font-size: 20px">اسم الفئة </label>
                                            <input onkeydown="error()" type="text"
                                                class="form-control {{ $errors->first('name') ? 'is-invalid' : '' }}"
                                                value="{{ old('name') }}" style="font-size: 20px" name="name"
                                                placeholder="اسم الفئة">

                                            <div id="error" class="text-danger">{{ $errors->first('name') }}</div>

                                        </div>


                                        <div class="row clearfix">



                                            <div class="col-lg-12">
                                                <label style="font-size: 20px"> الصورة العامة للفئة </label>

                                                <input type="file" width="590px" height="390px" class="dropify"
                                                    name="image">
                                            </div>

                                        </div>


                                        <div class="form-group">
                                            <label style="font-size: 20px">حالة الفئة</label>
                                            <div class="custom-control custom-switch">
                                                <input type="checkbox" class="custom-control-input" name="status"
                                                    id="status" @if (old('status') == 'on')
                                                checked @endif>
                                                <label class="custom-control-label" style="font-size: 20px"
                                                    for="status">تفعيل</label>

                                            </div>
                                        </div>

                                    </div>
                                </div>
                                <div>
                                    <button style="font-size: 20px" class="btn btn-sm btn-primary" type="submit"> إضافة
                                    </button>


                                </div>

                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('script')
    <script>
        function error() {
            document.getElementById('error').hidden = true;
        }

    </script>

@endsection

resources/views/cms/categories/edit.blade.php
@extends('cms.parent')
@section('title', 'الفئات')

@section('content')
    <div id="main-content">
        <div class="container-fluid">
            <div class="block-header">
                <div class="row clearfix">
                    <div class="col-md-6 col-sm-12">
                        <h1 style="font-size: 20px">فئة جديدة</h1>
                        <nav aria-label="breadcrumb">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="#" style="font-size: 20px">الرئيسية</a></li>
                                <li class="breadcrumb-item"><a href="{{ route('category.index') }}"
                                        style="font-size: 20px">الفئات</a></li>
                                <li class="breadcrumb-item active" aria-current="page" style="font-size: 20px">فئة جديدة
                                </li>
                            </ol>
                        </nav>
                    </div>
                    <div class="col-md-6 col-sm-12 text-right hidden-xs">
                        {{-- <a
                            href="https://themeforest.net/item/oculux-bootstrap-4x-admin-dashboard-clean-modern-ui-kit/23091507"
                            class="btn btn-sm btn-success" title="Themeforest"><i class="icon-basket"></i> Buy Now</a>
                        --}}
                    </div>
                </div>
            </div>

            <div class="row clearfix">
                <div class="col-sm-12">
                    <div class="card">
                        <div class="body">
                            <form method="POST" action="{{ route('category.update', [$category->token]) }}"
                                enctype="multipart/form-data">


                                {{-- @if ($errors->any())
                                    <div class="alert alert-danger alert-dismissible fade show" role="alert">
                                        <ul>
                                            @foreach ($errors->all() as $error)
                                                <li>{{ $error }}</li>
                                            @endforeach
                                        </ul>
                                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                    </div>
                                @endif --}}
                                @if (session()->has('message'))
                                    <div class="alert {{ session()->get('status') }} alert-dismissible fade show"
                                        role="alert">
                                        <span> {{ session()->get('message') }}</span>
                                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                @endif
                                @csrf
                                @method("PUT")
                                <div class="form-group row">
                                    <div class="col-md-10 col-sm-10">

                                        <div class="form-group">
                                            <label style="font-size: 20px">اسم الفئة </label>
                                            <input onkeydown="error()" type="text"
                                                class="form-control {{ $errors->first('name') ? 'is-invalid' : '' }}"
                                                value="{{ $category->name }}" style="font-size: 20px" name="name"
                                                placeholder="اسم الفئة">

                                            <div id="error" class="text-danger">{{ $errors->first('name') }}</div>

                                        </div>


                                        <div class="row clearfix">



                                            <div class="col-lg-12">
                                                <label style="font-size: 20px"> الصورة العامة للفئة </label>

                                                <input type="file" width="590px" height="390px" class="dropify"
                                                    data-default-file="{{ url('images/categories/' . $category->image) }}"
                                                    data-default-file="" name="image">
                                            </div>

                                        </div>


                                        <div class="form-group">
                                            <label style="font-size: 20px">حالة الفئة</label>
                                            <div class="custom-control custom-switch">
                                                <input type="checkbox" class="custom-control-input" name="status"
                                                    id="status" @if ($category->status == 'Visible')
                                                checked @endif>
                                                <label class="custom-control-label" style="font-size: 20px"
                                                    for="status">تفعيل</label>

                                            </div>
                                        </div>

                                    </div>
                                </div>
                                <div>
                                    <button style="font-size: 20px" class="btn btn-sm btn-primary" type="submit"> إضافة
                                    </button>


                                </div>

                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('script')
    <script>
        function error() {
            document.getElementById('error').hidden = true;
        }

    </script>

@endsection

resources/views/cms/categories/index.blade.php
@extends('cms.parent')
@section('title','الفئات')

@section('content')

    <div id="main-content">
        <div class="container-fluid">
            <div class="block-header">
                <div class="row clearfix">
                    <div class="col-md-6 col-sm-12">
                        <nav aria-label="breadcrumb">
                            <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="#" style="font-size: 20px">الرئيسية</a></li>
                            <li class="breadcrumb-item " style="font-size: 20px" aria-current="page">الفئات</li>
                            </ol>
                        </nav>
                    </div>
                    <div class="col-md-6 col-sm-12 text-right hidden-xs">
                    <a href="{{route('category.create')}}" class="btn btn-sm btn-primary" title="">فئة جديدة</a>
                        {{-- <a href="https://themeforest.net/item/oculux-bootstrap-4x-admin-dashboard-clean-modern-ui-kit/23091507" class="btn btn-sm btn-success" title="Themeforest"><i class="icon-basket"></i> Buy Now</a> --}}
                    </div>
                </div>
            </div>

            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12">
                    <div class="card">
                        <div class="header">
                            <h2 style="font-size: 20px">الفئات</h2>

                        </div>
                        <div class="table-responsive">
                            <table class="table table-hover js-basic-example dataTable table-custom spacing5 mb-0">
                                <thead>
                                    <tr>
                                        <th >#</th>
                                          <th style="font-size: 17px">صورة الفئة</th>
                                        <th style="font-size: 17px">الفئة</th>
                                        {{-- <th style="font-size: 17px">منتجات الفئة</th> --}}
                                        <th style="font-size: 17px">حالة الفئة</th>

                                        {{-- <th style="font-size: 17px">منتجات الفئة</th> --}}
                                        <th style="font-size: 17px">الإعدادات</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <span hidden>{{$i=0}}</span>
                                    @foreach ($categories as $category)
                                <span hidden>{{$i++}}</span>

                                    <tr>
                                    <td>{{$i}}</td>
                                        <td class="w60">
                                            <img src="{{url('images/categories/'.$category->image)}}" data-toggle="tooltip" data-placement="top" title="Avatar Name" alt="Avatar" class="w35 h35 rounded">
                                        </td>

                                    <td><span style="font-size: 17px">{{$category->name}}</span></td>
                                      {{-- <td>
                                            <a class="btn btn-info btn-sm"
                                               href="{{route('category.product',[$category->id])}}">
                                                <i class="icon-note">
                                                </i>
                                                ({{$category->product_count}}) عدد المنتجات
                                            </a>
                                            <span class="badge badge-dark"></span>
                                        </td> --}}
                                     <td>
                                         @if($category->status=='Visible')
                                        <span style="font-size: 17px" class="badge badge-success">نشطة</span>
                                        @else
                                    <span style="font-size: 17px" class="badge badge-danger">متوقفة</span>
                                        @endif

                                    </td>
                                        <td>
                            <a href="{{route('category.edit',[$category->token])}}" type="button" style="font-size: 20px" class="btn btn-sm btn-default" title="تعديل"><i class="fa fa-edit"></i> تعديل</a>
                                        <a onclick="confirmDelete(this, '{{$category->token}}')" type="button" style="font-size: 20px" class="btn btn-sm btn-default js-sweetalert" title="حذف" data-type="confirm"><i class="fa fa-trash-o text-danger"> حذف </i></a>


                                        </td>




                                        {{-- <td>
                                            <a href="javascript:void(0);" class="btn btn-info btn-round">Interview</a>

                                        </td> --}}
                                    </tr>
                                         @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
@endsection
@section('script')
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>

    <script>
        function confirmDelete(app, id) {
            Swal.fire({
                title: 'هل انت متأكد من الحذف ؟',
                text: "لن تكون قادرا على استرجاعها",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'حذف',
                cancelButtonText:'تراجع'
            }).then((result) => {
                if (result.value) {
                    deletecategory(app, id)
                }
            })
        }

        function deletecategory(app, id) {
            axios.delete('/cms/category/' + id)
                .then(function (response) {
                    // handle success (Status Code: 200)
                    console.log(response);
                    console.log(response.data);
                    showMessage(response.data);
                    app.closest('tr').remove();
                })
                .catch(function (error) {
                    // handle error (Status Code: 400)
                    console.log(error);
                    console.log(error.response.data);
                    showMessage(error.response.data);
                })
                .then(function () {
                    // always executed
                });
        }

        function showMessage(data) {
            Swal.fire({
                position: 'center',
                icon: data.icon,
                title: data.title,
                showConfirmButton: false,
                timer: 1500
            })
        }
    </script>

@endsection